#!/usr/bin/env bash
# Generate version.tex, which stamps the current git revision into the documents.
#
# Defines, for actsdoc.sty:
#   \gitrev   the revision, e.g. "main @ 50d815f" or "50d815f (modified)"
#   \gitdate  commit date of HEAD (ISO, UTC)
#
# Document *versions* are declared in the .tex preamble via actsdoc's version
# option, not derived from git; this only records which commit a PDF came from.
#
# Usage: scripts/gitversion.sh [output-file]   (default: version.tex)

set -euo pipefail

out="${1:-version.tex}"

if ! git rev-parse --git-dir >/dev/null 2>&1; then
    rev="not a git checkout"
    date="$(date -u +%Y-%m-%d)"
else
    rev="$(git rev-parse --short HEAD)"
    date="$(git show -s --format=%cs HEAD)"

    branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo HEAD)"
    # CI checkouts are often detached; prefer the ref name the workflow was given.
    if [ "$branch" = "HEAD" ] && [ -n "${GITHUB_REF_NAME:-}" ]; then
        branch="$GITHUB_REF_NAME"
    fi
    [ "$branch" = "HEAD" ] || rev="$branch @ $rev"

    # Flag uncommitted changes, which only happens in local builds.
    git diff --quiet HEAD -- 2>/dev/null || rev="$rev (modified)"
fi

# Escape the handful of characters that are special to LaTeX and can plausibly
# show up in a branch name.
escape() {
    printf '%s' "$1" | sed -e 's/\\/\\textbackslash{}/g' \
                           -e 's/\([&%$#_{}]\)/\\\1/g' \
                           -e 's/~/\\textasciitilde{}/g' \
                           -e 's/\^/\\textasciicircum{}/g'
}

cat > "$out" <<TEX
% Generated by scripts/gitversion.sh -- do not edit, do not commit.
\\providecommand{\\gitrev}{}\\renewcommand{\\gitrev}{$(escape "$rev")}
\\providecommand{\\gitdate}{}\\renewcommand{\\gitdate}{$(escape "$date")}
TEX

echo "$out: rev=$rev date=$date"
